import os
import json
from pathlib import Path

from groq import Groq
from dotenv import load_dotenv

from prompts import SYSTEM_PROMPT

# -------------------------------------------------
# Load Environment Variables
# -------------------------------------------------

env_path = Path(__file__).resolve().parent.parent / ".env"

load_dotenv(env_path)

API_KEY = os.getenv("GROQ_API_KEY")

MODEL = os.getenv(
    "MODEL_NAME",
    "llama-3.3-70b-versatile"
)

if not API_KEY:
    raise Exception("GROQ_API_KEY not found in .env")

client = Groq(api_key=API_KEY)


# -------------------------------------------------
# Generic Chat Function
# -------------------------------------------------

def chat(prompt, temperature=0.2):

    completion = client.chat.completions.create(

        model=MODEL,

        temperature=temperature,

        messages=[

            {

                "role": "system",

                "content": SYSTEM_PROMPT

            },

            {

                "role": "user",

                "content": prompt

            }

        ]

    )

    return completion.choices[0].message.content


# -------------------------------------------------
# AI Tutor
# -------------------------------------------------

def ask_groq(question, level):

    prompt = f"""

Student Level:
{level}

Question:
{question}

Explain according to the student's level.

Always include:

1. Explanation

2. Real World Example

3. Best Practices

4. Practice Exercise

"""

    return chat(prompt)


# -------------------------------------------------
# AI Quiz Generator
# -------------------------------------------------

def generate_quiz(

        topic,

        difficulty,

        number_of_questions

):

    prompt = f"""

Generate exactly {number_of_questions}
multiple choice cybersecurity questions.

Topic:

{topic}

Difficulty:

{difficulty}

Return ONLY valid JSON.

Format:

{{
    "questions":[
        {{
            "question":"",

            "options":[
                "",
                "",
                "",
                ""
            ],

            "answer":"",

            "explanation":""
        }}
    ]
}}

Do not return markdown.

Do not return code blocks.

Only JSON.

"""

    result = chat(

        prompt,

        temperature=0.3

    )

    try:

        return json.loads(result)

    except:

        return {

            "raw_response": result,

            "error": "Invalid JSON generated by model."

        }


# -------------------------------------------------
# Interview Generator
# -------------------------------------------------

def generate_interview(role):

    prompt = f"""

You are an interviewer.

Conduct a cybersecurity interview for

{role}

Generate

10 interview questions.

After every question,

leave space for the student answer.

"""

    return chat(prompt)


# -------------------------------------------------
# Learning Roadmap
# -------------------------------------------------

def generate_roadmap(

        goal,

        level

):

    prompt = f"""

Create a cybersecurity roadmap.

Career Goal:

{goal}

Current Skill:

{level}

Include

Phase 1

Phase 2

Phase 3

Recommended Certifications

Recommended Projects

Recommended Labs

Recommended Resources

Timeline

"""

    return chat(prompt)
